name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'bwagner5/eks-charts-shadow'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
      - run: make install-toolchain
      - run: make verify
      - run: make package
