name: release
on:
  push:
    branches: [master]
    tags:
      - "v*.*.*"
  workflow_dispatch:
permissions:
  id-token: write
  pull-requests: write
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'bwagner5/eks-charts-shadow'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/
            ~/go/bin/
          key: ${{ runner.os }}-go-cache-${{ hashFiles('scripts/install-toolchain.sh') }}
      - run: make install-toolchain
      - run: make verify
      - run: make package publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
